# scalefree_dist_number
SLE_dist: [0,25,50,75,100]
#SLE_dist: [0]
#SLE_dist: [25]
#SLE_dist: [50]
#SLE_dist: [75]
#SLE_dist: [100]
n: 200
nSLE_min: 2
nSLE_max: 100
dnSLE: 2
run_dt: 0.05
run_t: 10000
start: 150
T_window: 100
sampling_rate: 1500
tau_max: 150
times: 10
single_times: 0